# remote_theme: wthomare/jekyll-theme-prologue
# collections: [sections]
#
# They activate the theme and tell Jekyll to find your homepage content
# in /_sections. Note where "sections" starts with an underscore
# and where it doesn't. The social settings will make links to
# Twitter, etc., but only if you give the URL.
#
# Also, be sure to customize url and baseurl for your site.
#
# Site settings
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wilfried Thomaré
subtitle: Market Access Developer
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
author: Your Incredible Name
email: wilfried.thomare@gmail.com
avatar: assets/images/avatar.png

# You'll want to customize url and baseurl for your own site:
baseurl: "/jekyll-theme-prologue" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url:
facebook_url: https://www.facebook.com/
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/wilfried-thomare-67bbb387/
github_url: https://github.com/wthomare
stackoverflow_url:
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
collections: [sections]
